### PR TITLE
Add support for new (puppet-strings) rdoc @param parameters

### PR DESCRIPTION
**Pull request by vStone**

### CODE REVIEW

**Comment by vStone** [comment]
See https://github.com/puppetlabs/puppetlabs-strings#classes--defined-types

**Comment by domcleal** [comment]
Let me fix those build errors on master for you first...

**Comment by vStone** [comment]
```bash
while true; do
 git fetch upstream; git rebase upstream/master; sleep 1;
done;
```

**Comment by domcleal** [comment]
Merged, thanks @vStone! I'll cut a new release for you.

**Comment by domcleal** [comment]
v1.4.0's out, enjoy.

**Pull request merged**
